'use client';
import { useEffect, useState } from 'react';
import { trip } from '../data';
import CopyButton from './CopyButton';

const DB='royal-oak-trip-docs-v2';
const STORE='docs';
function openDb(){return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined')return reject(new Error('Offline document storage is unavailable in this browser.'));const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function putOffline(key,payload){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(payload,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function getOffline(key){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error)})}

export default function AirportDocs(){
  const [pin,setPin]=useState('');
  const [unlocked,setUnlocked]=useState(false);
  const [msg,setMsg]=useState('');
  const [offline,setOffline]=useState({});
  const [saving,setSaving]=useState(false);
  const [meta,setMeta]=useState(null);
  const [counter,setCounter]=useState(false);
  useEffect(()=>{trip.airportDocs.forEach(async d=>{try{if(await getOffline(d.id))setOffline(o=>({...o,[d.id]:true}))}catch{}})},[]);
  const urlFor=d=>d.privateKey?`/api/vault/file?name=${encodeURIComponent(d.privateKey)}`:d.href;
  async function fetchDoc(d){const r=await fetch(urlFor(d),{credentials:'include'});if(!r.ok){let e='Document unavailable';try{e=(await r.json()).error||e}catch{}throw new Error(e)}return r.blob()}
  async function unlock(){setMsg('');try{const r=await fetch('/api/vault/unlock',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not unlock vault');setUnlocked(true);setPin('');const mr=await fetch('/api/vault/file?name=meta',{credentials:'include'});if(mr.ok)setMeta(await mr.json());setMsg('Private Travel Vault unlocked for this browser session.')}catch(e){setUnlocked(false);setMsg(e.message)}}
  async function openDoc(d){try{const saved=await getOffline(d.id);const blob=saved?.blob||await fetchDoc(d);const u=URL.createObjectURL(blob);window.open(u,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(u),60000)}catch(e){setMsg(e.message)}}
  async function saveDoc(d){try{const blob=await fetchDoc(d);await putOffline(d.id,{blob,filename:d.filename,type:blob.type,savedAt:new Date().toISOString()});setOffline(o=>({...o,[d.id]:true}));setMsg(`${d.title} saved offline on this device.`)}catch(e){setMsg(e.message)}}
  async function saveAll(){setSaving(true);let ok=0,fail=0;for(const d of trip.airportDocs){try{const blob=await fetchDoc(d);await putOffline(d.id,{blob,filename:d.filename,type:blob.type,savedAt:new Date().toISOString()});setOffline(o=>({...o,[d.id]:true}));ok++}catch{fail++}}setSaving(false);setMsg(`${ok} document(s) saved offline${fail?`; ${fail} could not be saved — unlock the vault and retry.`:'.'}`)}
  return <section className="section" role="region" aria-label="Airport documents">
    <div className="grid" style={{marginBottom:16}}><div className="card"><div className="label">CHECK-IN</div><div className="kpi good">SUCCESS</div><div className="muted">Both outbound segments checked in.</div></div><div className="card"><div className="label">SELF-PRINT FOR FLIGHT</div><div className="kpi">NONE</div><div className="muted">Air France issues the boarding pass at RBA.</div></div><div className="card"><div className="label">PHYSICAL MUST-HAVE</div><div className="kpi warn">PASSPORT</div><div className="muted">Original U.S. passport; digital copy is backup only.</div></div></div>
    <section className="card section"><h2>Airport quick reference</h2><div style={{overflowX:'auto'}}><table><thead><tr><th>Item</th><th>Status / value</th><th>Meaning</th></tr></thead><tbody>{trip.airportQuick.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div><div className="toolbar no-print" style={{marginTop:12}}><button onClick={()=>setCounter(v=>!v)}>{counter?'Hide':'Show'} Counter Mode</button></div>{counter&&<div className="counter"><div>PRENTISS Benjamin</div><div>DL8491 • RBA 10:35 → CDG 14:40 • Seat 22D • Boarding 10:05</div><div>DL8719 • CDG 16:05 → DTW 18:50 • Seat 38H • Boarding 15:10</div><div>CHECKED IN — BOARDING PASS MUST BE ISSUED AT RBA</div></div>}</section>
    <section className="card section"><h2>Private Travel Vault</h2><p className="muted">Passport, license, exact Detroit contact data and Air France booking details are not public static files. They require a server-side vault unlock.</p>{!unlocked?<div className="toolbar"><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Travel Vault PIN" autoComplete="current-password"/><button onClick={unlock}>Unlock vault</button></div>:<span className="pill good">Vault unlocked</span>}{msg&&<p className="muted">{msg}</p>}{meta&&<div className="copyGrid" style={{marginTop:14}}><div><b>Delta confirmation</b><div className="copyLine"><code>{meta.deltaConfirmation}</code><CopyButton text={meta.deltaConfirmation} label="Delta confirmation"/></div></div><div><b>Air France booking</b><div className="copyLine"><code>{meta.airFranceBooking}</code><CopyButton text={meta.airFranceBooking} label="Air France booking"/></div></div><div><b>Original Delta ticket</b><div className="copyLine"><code>{meta.originalDeltaTicket}</code><CopyButton text={meta.originalDeltaTicket} label="Delta ticket"/></div></div><div><b>Air France check-in ticket</b><div className="copyLine"><code>{meta.airFranceCheckinTicket}</code><CopyButton text={meta.airFranceCheckinTicket} label="Air France ticket"/></div></div></div>}<div className="toolbar no-print" style={{marginTop:12}}><button onClick={saveAll} disabled={saving}>{saving?'Saving…':'Save ALL docs offline on this device'}</button></div><p className="muted" style={{fontSize:12}}>Offline saving deliberately places copies in this browser's device storage so you can reach them without airport Wi-Fi. Use only on your own locked device.</p></section>
    <div className="docGrid section">{trip.airportDocs.map(d=><article className="card doc" key={d.id}><div className="docTop"><div><div className="label">{d.kind}</div><h3>{d.title}</h3></div><span className={`pill ${offline[d.id]?'good':''}`}>{offline[d.id]?'OFFLINE':'NOT SAVED'}</span></div><p className="muted">{d.description}</p><div className="toolbar no-print"><button onClick={()=>openDoc(d)}>{offline[d.id]?'Open offline':'Open'}</button><button className="btn-secondary" onClick={()=>saveDoc(d)}>Save offline</button></div></article>)}</div>
    <section className="card section" style={{borderColor:'var(--warn)'}}><h2>Printing rules</h2><p><strong>Flight:</strong> nothing must be printed by you. Air France must issue the boarding pass at RBA. <strong>PennDOT:</strong> the temporary driver-license/camera-card document separately says it should be printed for your records and has a signature line. That is for driving/rental documentation, not flight boarding.</p></section>
  </section>;
}
